/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.basicclass.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.rm2pt.sample.basicclass.ide.contentassist.antlr.internal.InternalDslParser;
import org.rm2pt.sample.basicclass.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPersonAccess().getAlternatives(), "rule__Person__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup_4(), "rule__Class__Group_4__0");
			builder.put(grammarAccess.getClassAccess().getGroup_4_3(), "rule__Class__Group_4_3__0");
			builder.put(grammarAccess.getStudentAccess().getGroup(), "rule__Student__Group__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_4(), "rule__Student__Group_4__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_4_3(), "rule__Student__Group_4_3__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_5(), "rule__Student__Group_5__0");
			builder.put(grammarAccess.getStudentAccess().getGroup_5_3(), "rule__Student__Group_5_3__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup(), "rule__Teacher__Group__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_4(), "rule__Teacher__Group_4__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_4_3(), "rule__Teacher__Group_4_3__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_5(), "rule__Teacher__Group_5__0");
			builder.put(grammarAccess.getTeacherAccess().getGroup_5_3(), "rule__Teacher__Group_5_3__0");
			builder.put(grammarAccess.getClassAccess().getNameAssignment_2(), "rule__Class__NameAssignment_2");
			builder.put(grammarAccess.getClassAccess().getMembersAssignment_4_2(), "rule__Class__MembersAssignment_4_2");
			builder.put(grammarAccess.getClassAccess().getMembersAssignment_4_3_1(), "rule__Class__MembersAssignment_4_3_1");
			builder.put(grammarAccess.getStudentAccess().getNameAssignment_2(), "rule__Student__NameAssignment_2");
			builder.put(grammarAccess.getStudentAccess().getStudentsAssignment_4_2(), "rule__Student__StudentsAssignment_4_2");
			builder.put(grammarAccess.getStudentAccess().getStudentsAssignment_4_3_1(), "rule__Student__StudentsAssignment_4_3_1");
			builder.put(grammarAccess.getStudentAccess().getTeachersAssignment_5_2(), "rule__Student__TeachersAssignment_5_2");
			builder.put(grammarAccess.getStudentAccess().getTeachersAssignment_5_3_1(), "rule__Student__TeachersAssignment_5_3_1");
			builder.put(grammarAccess.getTeacherAccess().getNameAssignment_2(), "rule__Teacher__NameAssignment_2");
			builder.put(grammarAccess.getTeacherAccess().getStudentsAssignment_4_2(), "rule__Teacher__StudentsAssignment_4_2");
			builder.put(grammarAccess.getTeacherAccess().getStudentsAssignment_4_3_1(), "rule__Teacher__StudentsAssignment_4_3_1");
			builder.put(grammarAccess.getTeacherAccess().getTeachersAssignment_5_2(), "rule__Teacher__TeachersAssignment_5_2");
			builder.put(grammarAccess.getTeacherAccess().getTeachersAssignment_5_3_1(), "rule__Teacher__TeachersAssignment_5_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
